#!/bin/bash
FOREGROUND="#ffbc42"
PADDINGS="40% 0 0 37%"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${FOREGROUND:-#000000}; spacing: $PADDINGS;}")

power_off=
reboot=
lock=
suspend=鈴
log_out=
//log_out=test

options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"
chosen="$(echo -e "$options" | rofi "${ROFI_OPTIONS[@]}" -dmenu -selected-row 2)"

PADDINGS="40% 0 0 46%"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${FOREGROUND:-#000000}; spacing: $PADDINGS;}")
YESNO="\n"

case $chosen in
    $power_off)
        [ $(echo -e $YESNO | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #D81159;}" -dmenu -i -p "Are you shure you want to proceed?") ==  ] && systemctl poweroff
        ;;
    $reboot)
        [ $(echo -e $YESNO | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #D81159;}" -dmenu -i -p "Are you shure you want to proceed?") ==  ] && systemctl reboot
        ;;
    $lock)
	    exec  dm-tool lock;
        ;;
    $suspend)
	    [ $(echo -e $YESNO | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #D81159;}" -dmenu -i -p "Are you shure you want to proceed?") ==  ] && systemctl suspend
        ;;
    $log_out)
	    [ $(echo -e $YESNO | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: #D81159;}" -dmenu -i -p "Are you shure you want to proceed?") ==  ] && bspc quit
        ;;
esac
